fix: allow for local web debug builds

diff --git a/run b/run
--- a/run
+++ b/run
@@ -167,6 +167,7 @@ web_debug(){
     exit 0
   fi
   debug=true
+  prepare_local
   clean_web
   export_web
   web_server &
@@ -402,7 +403,10 @@ prepare_ci_gettemplates(){
   fi
   echo "Will get the custom templates for ${GODOT_VERSION}"
   echo "wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip"
-  wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip
+  wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip || {
+    echo "Templates for \`${GODOT_VERSION}\` not found"
+    exit 1
+  }
   echo "✓ Downloaded templates"
   echo "Will unzip templates"
   echo "unzip $(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip -d templates"
