fix: ensure canvas resolution scales with the parent containers to avoid blurry fonts (#585)

diff --git a/run b/run
--- a/run
+++ b/run
@@ -166,6 +166,7 @@ web_debug(){
     echo "be in your \$PATH"
     exit 0
   fi
+  echo "You need the custom templates. Please make sure to run prepare:local at least once!"
   debug=true
   clean_web
   export_web
@@ -402,7 +403,10 @@ prepare_ci_gettemplates(){
   fi
   echo "Will get the custom templates for ${GODOT_VERSION}"
   echo "wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip"
-  wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip
+  wget https://github.com/Razoric480/godot/releases/download/${GODOT_VERSION}-parser/$(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip || {
+    echo "Templates for \`${GODOT_VERSION}\` not found"
+    exit 1
+  }
   echo "✓ Downloaded templates"
   echo "Will unzip templates"
   echo "unzip $(sed 's/\.//g' <<< ${GODOT_VERSION})custom-templates.zip -d templates"
