chore: split tasks for better debugging

diff --git a/.github/workflows/BuildGodot.yaml b/.github/workflows/BuildGodot.yaml
--- a/.github/workflows/BuildGodot.yaml
+++ b/.github/workflows/BuildGodot.yaml
@@ -23,14 +23,19 @@ jobs:
         run: |
           mkdir -v -p ~/.local/share/godot/templates
           mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
+      - name: Install Necessary Software
+        run: |
+          apt-get update && apt-get install -y --no-install-recommends sed 
       - name: Web Build
         run: |
           mkdir -v -p build/web && \
           godot -v --export "HTML5" build/web/index.html || true && \
-          cd build/web && \
-          echo "built godot" && \
+          echo "built godot"
+      - name: Add Git Hash to build
+        run: |
+          cd build/web
           sed -i "0,/<script/{s/<script/<div style='position:absolute;bottom:5px;right:5px;z-index:2;font-size:.8em;font-family:monospace;color:#737373;'>$GITHUB_REF:$GITHUB_SHA<\/div><script/}" index.html && \
-          echo "added commit hash to index.html"
+          echo "added commit hash to index.html" || echo "failed to add the commit hash"
       - name: Upload Artifact
         uses: actions/upload-artifact@v1
         with:
